### ISSUE TITLE
Learn guide suggest to use lambda function to deal with touchio

### ISSUE THREAD

**Issue by dglaude** [adafruit/Adafruit_CircuitPython_Debouncer#23]
I wanted to use Debouncer with touchio input.

So I went to the learn guide: https://learn.adafruit.com/debouncer-library-python-circuitpython-buttons-sensors/advanced-debouncing

But maybe that part is outdated (I still like to learn about lambda function) because #8 made it more simple to use Debouncer with touchio.

Nothing to fix in the code of this library (except maybe a simpletest_touchio.py that demonstrate that usecase) but the guide could get some update.

**Comment by FoamyGuy** [comment]
Thanks for the suggestion @dglaude! I will work on updating the learn guide to also show the new simpler way to use the debouncer lib with touchio.

**Comment by FoamyGuy** [comment]
I've updated the Basic Debouncing page to note about the library working with TouchIn. As well as a link to the examples directory in this repo.
