### ISSUE TITLE
Weirdness with PyPortals

### ISSUE THREAD

**Issue by evaherrada** [adafruit/Adafruit_CircuitPython_Debouncer#28]
Hey, so for a project I'm working on, I was adapting [this code](https://learn.adafruit.com/funhouse-door-alert-email-notification/code-the-funhouse-door-alert) to run on the PyPortal. Now, the code works perfectly on the Titano, but on the Pynt, switch.state is always 3 no matter what.

In both cases I'm using a 3-pin JST to alligator clip on the side of the board.

I also tried this code on a Feather M4 and it worked perfectly.

Relevant parts of my code:
```
switch_pin = DigitalInOut(board.D4)
switch_pin.direction = Direction.INPUT
switch_pin.pull = Pull.UP
switch = Debouncer(switch_pin)

while True:
    switch.update()
    print(switch.state)

    if switch.rose:
        print("Door is open")
        io.publish("door", 0)
        print("sent")

    if switch.fell:
        print("Door is closed")
        io.publish("door", 1)
        print("sent")
```
[Full code](https://github.com/dherrada/Adafruit_Learning_System_Guides/blob/iot-hub/FunHouse_IOT_Hub/door_daughter.py). In that code, it's using a Feather M4, so I set the pin to D10

**Comment by brentru** [comment]
@dherrada  The funhouse uses pullups on the btns, have you tried commenting out the pull mode for the pyportal?

**Comment by evaherrada** [comment]
@brentru I've figured it out. That wasn't it (it actually does need a pull up) but the reason why it wasn't working is really dumb. I was just looking at the pinouts to make sure there wasn't something weird going on with the pins, and sure enough, pins D3 and D4 are mislabeled, so when I was trying to use pin D4 I was actually plugged into D3.
