### ISSUE TITLE
readthedocs latest not up to date

### ISSUE THREAD

**Issue by Neradoc** [adafruit/Adafruit_CircuitPython_Debouncer#36]
The documentation link links to the "latest" but it's not up to date, while "stable" is.
https://docs.circuitpython.org/projects/debouncer/en/latest/api.html

**Comment by tekktrik** [comment]
I've seen a few across the repos, maybe it's worth compiling a list of builds to rerun?

**Comment by kattni** [comment]
Latest failed to build the last time it ran. Stable built successfully. Rerunning the latest build now to see if it passes.

**Comment by kattni** [comment]
Latest built successfully. @Neradoc Please verify they match. Closing this for now. We can reopen if something isn't right.

**Comment by tekktrik** [comment]
@kattni do you want me to create issues for similar repos?

**Comment by kattni** [comment]
@tekktrik Sure. I guess assign me the issue if you can, or tag me in the notes if you can't assign me. I'm probably the one who will end up dealing with them anyway.
