### ISSUE TITLE
Library adafruit_debouncer missing adafruit_ticks

### ISSUE THREAD

**Issue by cmora111** [adafruit/Adafruit_CircuitPython_Debouncer#43]
### CircuitPython version

```python
Adafruit CircuitPython 9.2 macropad rp2040
```

### Code/REPL

```python
File "adafruit_debouncer.py", line 32, in <module>
ImportError: no module named 'adafruit_ticks'
```

### Behavior

fails to load

### Description

  File "adafruit_debouncer.py", line 32, in <module>
ImportError: no module named 'adafruit_ticks'

**Comment by dhalbert** [comment]
`adafruit_ticks` is a a separate prerequisite library for `adafruit_debouncer`. You'll need to install it too. It's in the library bundle, and will also be installed automatically by `circup` when you install `adafruit_debouncer`.

**Comment by cmora111** [comment]
Thanks, I figured it out.
 
Carlos
